# Generated by Django 3.2.20 on 2023-07-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brieftitle',
            old_name='authors',
            new_name='call_number',
        ),
        migrations.AddField(
            model_name='brieftitle',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brieftitle',
            name='info_copyright',
            field=models.DateField(),
        ),
    ]
