# Generated by Django 3.2.20 on 2023-07-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_rename_ibsn_brieftitle_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brieftitle',
            name='extent',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='brieftitle',
            name='other_details',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
