# Generated by Django 3.2.20 on 2023-08-02 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_bookstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='brieftitle',
            name='book_status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='status_book', to='catalogue.bookstatus'),
            preserve_default=False,
        ),
    ]
