# Generated by Django 3.2.20 on 2023-08-03 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20230803_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ManyToManyField(related_name='patron_books', to='catalogue.BriefTitle')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrons', to='catalogue.patron')),
            ],
        ),
    ]
