# Generated by Django 3.2.20 on 2023-08-04 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_checkin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'ordering': ['-date_borrowed']},
        ),
        migrations.AddField(
            model_name='checkin',
            name='date_borrowed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkin',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='patron_books', to='catalogue.BriefTitle'),
        ),
    ]
