# Generated by Django 3.2.20 on 2023-09-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20230822_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
