# Generated by Django 3.2.20 on 2023-09-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_alter_checkin_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
