# Generated by Django 3.2.20 on 2023-09-10 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_alter_patron_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patron_position', to='catalogue.position'),
        ),
    ]
