# Generated by Django 3.2.20 on 2023-09-14 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0020_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookBorrowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_borrowed', models.DateField(auto_now_add=True)),
                ('books', models.ManyToManyField(related_name='borrowed_book', to='catalogue.BriefTitle')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_borrower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
