# Generated by Django 3.2.20 on 2023-09-19 00:16

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_alter_user_email'),
        ('catalogue', '0022_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('email', models.CharField(max_length=255)),
                ('contact_no', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('patron_id', models.ImageField(null=True, upload_to='images/')),
                ('password', models.CharField(max_length=255)),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register_patron_course', to='auth.usercourse')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register_patron_department', to='auth.userdepartment')),
                ('number_loc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register_patron_number_location', to='auth.usernumberlocation')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register_position', to='auth.userposition')),
            ],
        ),
    ]
