# Generated by Django 3.2.20 on 2023-09-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_alter_attendance_attendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(max_length=255)),
                ('date_registered', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
