# Generated by Django 3.2.20 on 2023-09-26 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_alter_user_email'),
        ('catalogue', '0028_bookreserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_patron_course', to='auth.usercourse'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_patron_department', to='auth.userdepartment'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_position', to='auth.userposition'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
