# Generated by Django 3.2.20 on 2023-10-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_auto_20230926_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('attendance_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-attendance_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-attendance_date']},
        ),
    ]
