# Generated by Django 3.2.20 on 2023-10-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_promethoenixdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='brieftitle',
            name='date_reserved',
            field=models.DateField(null=True),
        ),
    ]
