# Generated by Django 3.2.20 on 2023-11-04 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0034_bookborrowedhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookborrowedhistory',
            options={'ordering': ['-date_borrowed']},
        ),
        migrations.CreateModel(
            name='PaidFines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_paid', models.CharField(max_length=100)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_fines_patron', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
