# Generated by Django 3.2.20 on 2023-11-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0036_auto_20231104_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='FineRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('fine_rate', models.IntegerField()),
            ],
        ),
    ]
