# Generated by Django 3.2.20 on 2023-11-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0037_finerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='brieftitle',
            name='book_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='brieftitle',
            name='editor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
